### ISSUE TITLE
Various issues with parsing code line numbers correctly

### ISSUE THREAD

**Issue by acser123** [isene/xrpn#32]
Several issues here.
E2 is also not read properly.

$ cat -A lnum.hp41 
01 lbl "LNUM"$
002 1$
003 2$
 004 3$
^I005 4$
06 +$
  07 -$
^I^I^I^I08 5$
                                         09 6$
010 sin$
011 lbl 00$
012    E2$
   013 END$
$ xrpn -l lnum.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> pprg
01 bl "LNUM"
02 002 1
03 003 2
04 004 3
05 005 4
06 
07 
08 08 5
09 09 6
10 in
11 bl 00
12   e2
13 nd
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
>

**Comment by isene** [comment]
Please check this again after latest update since I did a few fixes that may have solved this as well.

BTW; I will begin updating version number when you tell me we can start doing that.

**Comment by isene** [comment]
I believe this is solved now... verify?

**Comment by acser123** [comment]
Will do later today or tomorrow. Sorry about the delay.

**Comment by acser123** [comment]
Great progress but still not perfect:

$ xrpn -l lnum.hp41 
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> pprg
01◆lbl "LNUM"
02 1
03 2
04 3
05 4
06 +
07 -
08 5
09 6
10 sin
11◆lbl 00
12    e2
13 end
------------------------------
T = 0.0000   α = 
Z = 0.0000
Y = 0.0000
X = 0.0000   L = 0.0000
> xeq "LNUM"
No such command: e2
------------------------------
T = 1.0000   α = 
Z = -5.0000
Y = 5.0000
X = 0.1045   L = 6.0000
>

**Comment by isene** [comment]
Can you send me the file you test with on e-mail (g@isene.com)?
